(() => {
  "use strict";

  const STORAGE_KEY = "hiragana-sprint-v3";

  const FONT_PROFILES = [
    {id:"standard",label:"Standard",difficulty:"Standard",gainMultiplier:1,wordGainMultiplier:1,penalty:13,family:'"Hiragino Kaku Gothic ProN","Yu Gothic","Noto Sans JP",sans-serif'},
    {id:"klee",label:"Klee pen",difficulty:"Medium",gainMultiplier:1.1,wordGainMultiplier:1.05,penalty:9,family:'"Hira Klee",sans-serif'},
    {id:"yuji-boku",label:"Yuji rough",difficulty:"Hard",gainMultiplier:1.2,wordGainMultiplier:1.1,penalty:7,family:'"Hira Yuji Boku",sans-serif'},
    {id:"yuji-syuku",label:"Yuji brush",difficulty:"Very hard",gainMultiplier:1.3,wordGainMultiplier:1.15,penalty:5,family:'"Hira Yuji Syuku",serif'},
    {id:"yuji-mai",label:"Yuji flowing",difficulty:"Very hard+",gainMultiplier:1.35,wordGainMultiplier:1.2,penalty:5,family:'"Hira Yuji Mai",serif'}
  ];
  const STANDARD_FONT=FONT_PROFILES[0];

  const GROUPS = [
    {id:"vowels", name:"Vowels", phase:"Basic", items:[["あ","a"],["い","i"],["う","u"],["え","e"],["お","o"]]},
    {id:"k", name:"K-row", phase:"Basic", items:[["か","ka"],["き","ki"],["く","ku"],["け","ke"],["こ","ko"]]},
    {id:"s", name:"S-row", phase:"Basic", items:[["さ","sa"],["し","shi"],["す","su"],["せ","se"],["そ","so"]]},
    {id:"t", name:"T-row", phase:"Basic", items:[["た","ta"],["ち","chi"],["つ","tsu"],["て","te"],["と","to"]]},
    {id:"n", name:"N-row", phase:"Basic", items:[["な","na"],["に","ni"],["ぬ","nu"],["ね","ne"],["の","no"]]},
    {id:"h", name:"H-row", phase:"Basic", items:[["は","ha"],["ひ","hi"],["ふ","fu"],["へ","he"],["ほ","ho"]]},
    {id:"m", name:"M-row", phase:"Basic", items:[["ま","ma"],["み","mi"],["む","mu"],["め","me"],["も","mo"]]},
    {id:"y", name:"Y-row", phase:"Basic", items:[["や","ya"],["ゆ","yu"],["よ","yo"]]},
    {id:"r", name:"R-row", phase:"Basic", items:[["ら","ra"],["り","ri"],["る","ru"],["れ","re"],["ろ","ro"]]},
    {id:"w", name:"W-row + ん", phase:"Basic", items:[["わ","wa"],["を","wo"],["ん","n"]]},
    {id:"g", name:"G-row", phase:"Voiced", items:[["が","ga"],["ぎ","gi"],["ぐ","gu"],["げ","ge"],["ご","go"]]},
    {id:"z", name:"Z-row", phase:"Voiced", items:[["ざ","za"],["じ","ji"],["ず","zu"],["ぜ","ze"],["ぞ","zo"]]},
    {id:"d", name:"D-row", phase:"Voiced", items:[["だ","da"],["ぢ","ji"],["づ","zu"],["で","de"],["ど","do"]]},
    {id:"b", name:"B-row", phase:"Voiced", items:[["ば","ba"],["び","bi"],["ぶ","bu"],["べ","be"],["ぼ","bo"]]},
    {id:"p", name:"P-row", phase:"Semi-voiced", items:[["ぱ","pa"],["ぴ","pi"],["ぷ","pu"],["ぺ","pe"],["ぽ","po"]]},
    {id:"kya", name:"K-combos", phase:"Combinations", items:[["きゃ","kya"],["きゅ","kyu"],["きょ","kyo"]]},
    {id:"sha", name:"SH-combos", phase:"Combinations", items:[["しゃ","sha"],["しゅ","shu"],["しょ","sho"]]},
    {id:"cha", name:"CH-combos", phase:"Combinations", items:[["ちゃ","cha"],["ちゅ","chu"],["ちょ","cho"]]},
    {id:"nya", name:"N-combos", phase:"Combinations", items:[["にゃ","nya"],["にゅ","nyu"],["にょ","nyo"]]},
    {id:"hya", name:"H-combos", phase:"Combinations", items:[["ひゃ","hya"],["ひゅ","hyu"],["ひょ","hyo"]]},
    {id:"mya", name:"M-combos", phase:"Combinations", items:[["みゃ","mya"],["みゅ","myu"],["みょ","myo"]]},
    {id:"rya", name:"R-combos", phase:"Combinations", items:[["りゃ","rya"],["りゅ","ryu"],["りょ","ryo"]]},
    {id:"gya", name:"G-combos", phase:"Combinations", items:[["ぎゃ","gya"],["ぎゅ","gyu"],["ぎょ","gyo"]]},
    {id:"ja", name:"J-combos", phase:"Combinations", items:[["じゃ","ja"],["じゅ","ju"],["じょ","jo"]]},
    {id:"bya", name:"B-combos", phase:"Combinations", items:[["びゃ","bya"],["びゅ","byu"],["びょ","byo"]]},
    {id:"pya", name:"P-combos", phase:"Combinations", items:[["ぴゃ","pya"],["ぴゅ","pyu"],["ぴょ","pyo"]]}
  ];

  const VISUAL = {
    "あ":["お","め"],"い":["り"],"う":["ら","つ"],"え":["ん"],"お":["あ","む"],
    "か":["や","ち"],"き":["さ"],"く":["へ","し"],"け":["は"],"こ":["に"],
    "さ":["き","ち"],"し":["つ","い","ひ"],"す":["む"],"せ":["そ"],"そ":["て","ん","せ"],
    "た":["な"],"ち":["さ","ら"],"つ":["し","う"],"て":["そ"],"と":["て"],
    "な":["た"],"に":["こ"],"ぬ":["め","ね"],"ね":["れ","わ","ぬ"],"の":["め"],
    "は":["ほ","け"],"ひ":["し","い"],"ふ":["う"],"へ":["く"],"ほ":["は","ま"],
    "ま":["ほ","よ"],"み":["ゆ"],"む":["す","お"],"め":["ぬ","の"],"も":["し"],
    "や":["か"],"ゆ":["み"],"よ":["ま"],"ら":["う","ち"],"り":["い"],
    "る":["ろ"],"れ":["ね","わ"],"ろ":["る"],"わ":["れ","ね"],"を":["お"],"ん":["そ"],
    "が":["か","ぎ"],"ぎ":["き","が"],"ぐ":["く","げ"],"げ":["け","ぐ"],"ご":["こ","げ"],
    "ざ":["さ","じ"],"じ":["し","ぢ"],"ず":["す","づ"],"ぜ":["せ"],"ぞ":["そ"],
    "だ":["た"],"ぢ":["ち","じ"],"づ":["つ","ず"],"で":["て"],"ど":["と"],
    "ば":["は","ぱ"],"び":["ひ","ぴ"],"ぶ":["ふ","ぷ"],"べ":["へ","ぺ"],"ぼ":["ほ","ぽ"],
    "ぱ":["は","ば"],"ぴ":["ひ","び"],"ぷ":["ふ","ぶ"],"ぺ":["へ","べ"],"ぽ":["ほ","ぼ"],
    "きゃ":["きゅ","きょ","ぎゃ"],"きゅ":["きゃ","きょ","ぎゅ"],"きょ":["きゃ","きゅ","ぎょ"],
    "しゃ":["しゅ","しょ","じゃ"],"しゅ":["しゃ","しょ","じゅ"],"しょ":["しゃ","しゅ","じょ"],
    "ちゃ":["ちゅ","ちょ"],"ちゅ":["ちゃ","ちょ"],"ちょ":["ちゃ","ちゅ"],
    "にゃ":["にゅ","にょ"],"にゅ":["にゃ","にょ"],"にょ":["にゃ","にゅ"],
    "ひゃ":["ひゅ","ひょ","びゃ","ぴゃ"],"ひゅ":["ひゃ","ひょ","びゅ","ぴゅ"],"ひょ":["ひゃ","ひゅ","びょ","ぴょ"],
    "みゃ":["みゅ","みょ"],"みゅ":["みゃ","みょ"],"みょ":["みゃ","みゅ"],
    "りゃ":["りゅ","りょ"],"りゅ":["りゃ","りょ"],"りょ":["りゃ","りゅ"],
    "ぎゃ":["きゃ","ぎゅ","ぎょ"],"ぎゅ":["きゅ","ぎゃ","ぎょ"],"ぎょ":["きょ","ぎゃ","ぎゅ"],
    "じゃ":["しゃ","じゅ","じょ"],"じゅ":["しゅ","じゃ","じょ"],"じょ":["しょ","じゃ","じゅ"],
    "びゃ":["ひゃ","ぴゃ","びゅ","びょ"],"びゅ":["ひゅ","ぴゅ","びゃ","びょ"],"びょ":["ひょ","ぴょ","びゃ","びゅ"],
    "ぴゃ":["ひゃ","びゃ","ぴゅ","ぴょ"],"ぴゅ":["ひゅ","びゅ","ぴゃ","ぴょ"],"ぴょ":["ひょ","びょ","ぴゃ","ぴゅ"]
  };

  const MNEMONICS = {
    "あ":"An apple has a stem through its round body: apple starts with ‘a’.",
    "い":"Two slim eels stand side by side, each squeaking ‘ee’.",
    "う":"A person bends over and says ‘ooh’ after being bumped.",
    "え":"An energetic runner crosses the finish line with arms spread.",
    "お":"A golfer hits a ball around an obstacle and shouts ‘oh!’",
    "か":"A kite catches on a pole; kite gives you the ‘k’ sound in ka.",
    "き":"A key has several teeth and a curved key ring: key sounds like ki.",
    "く":"A cuckoo’s open beak points left and calls ‘ku, ku.’",
    "け":"A keg stands beside a tap: keg begins with ke.",
    "こ":"Two coins lie in two neat rows: coins begin with ko.",
    "さ":"A samurai’s sword cuts across a curved body: samurai begins with sa.",
    "し":"A fishing hook sinks into the sea: sea sounds like shi.",
    "す":"A looped straw swirls through a drink: swirl begins with su.",
    "せ":"A sailor sets a line across a mast: sailor begins with se.",
    "そ":"A zigzag sewing thread finishes in a long curl: sewing begins with so.",
    "た":"The letters ‘t’ and ‘a’ seem tangled together: t + a gives ta.",
    "ち":"A cheerleader bends and raises a baton: cheer begins like chi.",
    "つ":"A tsunami wave curls toward the shore: tsunami begins with tsu.",
    "て":"A telephone receiver hangs from a horizontal shelf: telephone begins with te.",
    "と":"A toe catches a hanging splinter: toe begins with to.",
    "な":"A knot is tied around a cross-shaped post: knot gives the n sound in na.",
    "に":"Two needles lie beside a vertical thread: needle begins with ni.",
    "ぬ":"Noodles curl into a loop around a chopstick: noodles begin with nu.",
    "ね":"A net loops around a post and trails away: net begins with ne.",
    "の":"A single noodle makes one smooth loop: noodle begins with no.",
    "は":"A happy dancer stands beside a looping ribbon: happy begins with ha.",
    "ひ":"A smiling person stretches both arms: he grins and says hi.",
    "ふ":"Mount Fuji rises between drifting clouds: Fuji begins with fu.",
    "へ":"A pointed hill looks like a bent hiking path: hill helps recall he.",
    "ほ":"A holy cross stands beside two horizontal rays: holy begins with ho.",
    "ま":"A mast has two sails and a looping rope: mast begins with ma.",
    "み":"A musical note curls through three beats: music begins with mi.",
    "む":"A cow’s face ends in a curled ‘moo’: moo sounds like mu.",
    "め":"An eye is crossed by a loose line: eye reminds you of me looking.",
    "も":"A fishhook catches three pieces of moss: moss begins with mo.",
    "や":"A yak’s horns rise above its curved back: yak begins with ya.",
    "ゆ":"A unique fish swims inside a bowl: unique begins with yu.",
    "よ":"A yo-yo hangs from a short handle: yo-yo begins with yo.",
    "ら":"A rabbit’s ear bends over its round head: rabbit gives the r sound in ra.",
    "り":"Two reeds grow beside each other: reeds begin with ri.",
    "る":"A route curls into a complete loop before ending: route begins with ru.",
    "れ":"A reindeer’s antler rises beside a sweeping neck: reindeer begins with re.",
    "ろ":"A road makes an open loop without closing: road begins with ro.",
    "わ":"A wasp circles a post before flying away: wasp begins with wa.",
    "を":"A person walks around an obstacle; remember this particle is usually read ‘o.’",
    "ん":"The letter n is stretched into one long descending curve."
  };

  const WORDS = [
    {k:"あさ",r:"asa",m:"morning",u:["あ","さ"]},{k:"いえ",r:"ie",m:"house",u:["い","え"]},
    {k:"うえ",r:"ue",m:"above / on top",u:["う","え"]},{k:"あお",r:"ao",m:"blue",u:["あ","お"]},
    {k:"かお",r:"kao",m:"face",u:["か","お"]},{k:"ここ",r:"koko",m:"here",u:["こ"]},
    {k:"かさ",r:"kasa",m:"umbrella",u:["か","さ"]},{k:"すし",r:"sushi",m:"sushi",u:["す","し"]},
    {k:"そこ",r:"soko",m:"there",u:["そ","こ"]},{k:"せかい",r:"sekai",m:"world",u:["せ","か","い"]},
    {k:"たこ",r:"tako",m:"octopus",u:["た","こ"]},{k:"した",r:"shita",m:"below / under",u:["し","た"]},
    {k:"つき",r:"tsuki",m:"moon",u:["つ","き"]},{k:"とけい",r:"tokei",m:"clock / watch",u:["と","け","い"]},
    {k:"いぬ",r:"inu",m:"dog",u:["い","ぬ"]},{k:"ねこ",r:"neko",m:"cat",u:["ね","こ"]},
    {k:"なつ",r:"natsu",m:"summer",u:["な","つ"]},{k:"にく",r:"niku",m:"meat",u:["に","く"]},
    {k:"はな",r:"hana",m:"flower",u:["は","な"]},{k:"ひと",r:"hito",m:"person",u:["ひ","と"]},
    {k:"ふね",r:"fune",m:"boat",u:["ふ","ね"]},{k:"へや",r:"heya",m:"room",u:["へ","や"]},
    {k:"ほし",r:"hoshi",m:"star",u:["ほ","し"]},{k:"まち",r:"machi",m:"town",u:["ま","ち"]},
    {k:"みみ",r:"mimi",m:"ear",u:["み"]},{k:"むし",r:"mushi",m:"insect",u:["む","し"]},
    {k:"め",r:"me",m:"eye",u:["め"]},{k:"もも",r:"momo",m:"peach",u:["も"]},
    {k:"やま",r:"yama",m:"mountain",u:["や","ま"]},{k:"ゆめ",r:"yume",m:"dream",u:["ゆ","め"]},
    {k:"よる",r:"yoru",m:"night",u:["よ","る"]},{k:"そら",r:"sora",m:"sky",u:["そ","ら"]},
    {k:"りす",r:"risu",m:"squirrel",u:["り","す"]},{k:"くるま",r:"kuruma",m:"car",u:["く","る","ま"]},
    {k:"わに",r:"wani",m:"crocodile",u:["わ","に"]},{k:"わたし",r:"watashi",m:"I / me",u:["わ","た","し"]},
    {k:"かわ",r:"kawa",m:"river",u:["か","わ"]},{k:"しろ",r:"shiro",m:"white",u:["し","ろ"]},
    {k:"いろ",r:"iro",m:"color",u:["い","ろ"]},{k:"かぎ",r:"kagi",m:"key",u:["か","ぎ"]},
    {k:"みず",r:"mizu",m:"water",u:["み","ず"]},{k:"かぜ",r:"kaze",m:"wind",u:["か","ぜ"]},
    {k:"えいが",r:"eiga",m:"movie",u:["え","い","が"]},{k:"ごご",r:"gogo",m:"afternoon",u:["ご"]},
    {k:"でんわ",r:"denwa",m:"telephone",u:["で","ん","わ"]},{k:"げんき",r:"genki",m:"well / healthy",u:["げ","ん","き"]},
    {k:"だいがく",r:"daigaku",m:"university",u:["だ","い","が","く"]},{k:"ぞう",r:"zou",m:"elephant",u:["ぞ","う"]},
    {k:"ぶた",r:"buta",m:"pig",u:["ぶ","た"]},{k:"へび",r:"hebi",m:"snake",u:["へ","び"]},
    {k:"ぼうし",r:"boushi",m:"hat",u:["ぼ","う","し"]},{k:"さんぽ",r:"sanpo",m:"walk / stroll",u:["さ","ん","ぽ"]},
    {k:"しんぱい",r:"shinpai",m:"worry",u:["し","ん","ぱ","い"]},{k:"えんぴつ",r:"enpitsu",m:"pencil",u:["え","ん","ぴ","つ"]},
    {k:"きょう",r:"kyou",m:"today",u:["きょ","う"]},{k:"しゃしん",r:"shashin",m:"photo",u:["しゃ","し","ん"]},
    {k:"しゅみ",r:"shumi",m:"hobby",u:["しゅ","み"]},{k:"ちょきん",r:"chokin",m:"savings",u:["ちょ","き","ん"]},
    {k:"にゅうがく",r:"nyuugaku",m:"school enrollment",u:["にゅ","う","が","く"]},{k:"ひゃく",r:"hyaku",m:"one hundred",u:["ひゃ","く"]},
    {k:"みょうじ",r:"myouji",m:"surname",u:["みょ","う","じ"]},{k:"りょこう",r:"ryokou",m:"travel",u:["りょ","こ","う"]},
    {k:"ぎゅうにく",r:"gyuuniku",m:"beef",u:["ぎゅ","う","に","く"]},{k:"じゅぎょう",r:"jugyou",m:"class / lesson",u:["じゅ","ぎょ","う"]},
    {k:"びょういん",r:"byouin",m:"hospital",u:["びょ","う","い","ん"]}
  ];

  const EXTRA_WORDS = [
    ["あき","aki","autumn"],["あめ","ame","rain"],["いけ","ike","pond"],["いす","isu","chair"],
    ["うし","ushi","cow"],["うた","uta","song"],["うみ","umi","sea"],["えき","eki","station"],
    ["おか","oka","hill"],["おと","oto","sound"],["おなか","onaka","stomach"],["かみ","kami","paper"],
    ["かめ","kame","turtle"],["きた","kita","north"],["くち","kuchi","mouth"],["くも","kumo","cloud"],
    ["けさ","kesa","this morning"],["こえ","koe","voice"],["こめ","kome","uncooked rice"],["さかな","sakana","fish"],
    ["しお","shio","salt"],["しか","shika","deer"],["しま","shima","island"],["すな","suna","sand"],
    ["せなか","senaka","back"],["たま","tama","ball"],["ちず","chizu","map"],["つくえ","tsukue","desk"],
    ["て","te","hand"],["とり","tori","bird"],["なか","naka","inside"],["なまえ","namae","name"],
    ["にわ","niwa","garden"],["ぬの","nuno","cloth"],["のど","nodo","throat"],["はこ","hako","box"],
    ["はし","hashi","chopsticks"],["はる","haru","spring"],["ひる","hiru","noon"],["ふゆ","fuyu","winter"],
    ["ほね","hone","bone"],["まど","mado","window"],["みせ","mise","shop"],["みち","michi","road"],
    ["むら","mura","village"],["もの","mono","thing"],["もり","mori","forest"],["やさい","yasai","vegetables"],
    ["ゆき","yuki","snow"],["よこ","yoko","side"],["らいねん","rainen","next year"],["りんご","ringo","apple"],
    ["れきし","rekishi","history"],["ろく","roku","six"],["わかめ","wakame","seaweed"],["あたま","atama","head"],
    ["あに","ani","older brother"],["あね","ane","older sister"],["いもうと","imouto","younger sister"],["おとうと","otouto","younger brother"],
    ["おかあさん","okaasan","mother"],["おとうさん","otousan","father"],["かぞく","kazoku","family"],["ともだち","tomodachi","friend"],
    ["こども","kodomo","child"],["おとこ","otoko","man"],["おんな","onna","woman"],["おとな","otona","adult"],
    ["せんせい","sensei","teacher"],["がくせい","gakusei","student"],["がっこう","gakkou","school"],["きょうしつ","kyoushitsu","classroom"],
    ["としょかん","toshokan","library"],["ぎんこう","ginkou","bank"],["ゆうびんきょく","yuubinkyoku","post office"],["かいしゃ","kaisha","company"],
    ["しごと","shigoto","work"],["やすみ","yasumi","rest / holiday"],["じかん","jikan","time"],["いま","ima","now"],
    ["きのう","kinou","yesterday"],["まいにち","mainichi","every day"],["まいあさ","maiasa","every morning"],["まいばん","maiban","every night"],
    ["げつようび","getsuyoubi","Monday"],["かようび","kayoubi","Tuesday"],["すいようび","suiyoubi","Wednesday"],["もくようび","mokuyoubi","Thursday"],
    ["きんようび","kinyoubi","Friday"],["どようび","doyoubi","Saturday"],["にちようび","nichiyoubi","Sunday"],["いち","ichi","one"],
    ["に","ni","two"],["さん","san","three"],["よん","yon","four"],["ご","go","five"],
    ["なな","nana","seven"],["はち","hachi","eight"],["きゅう","kyuu","nine"],["じゅう","juu","ten"],
    ["ごはん","gohan","cooked rice / meal"],["あさごはん","asagohan","breakfast"],["ひるごはん","hirugohan","lunch"],["ばんごはん","bangohan","dinner"],
    ["たべもの","tabemono","food"],["のみもの","nomimono","drink / beverage"],["くだもの","kudamono","fruit"],["たまご","tamago","egg"],
    ["ぎゅうにゅう","gyuunyuu","milk"],["おちゃ","ocha","tea"],["こうちゃ","koucha","black tea"],["さとう","satou","sugar"],
    ["みそ","miso","miso"],["ぱん","pan","bread"],["うどん","udon","udon noodles"],["そば","soba","soba noodles"],
    ["りょうり","ryouri","cooking / cuisine"],["いく","iku","to go"],["くる","kuru","to come"],["かえる","kaeru","to return"],
    ["みる","miru","to see"],["きく","kiku","to listen / ask"],["よむ","yomu","to read"],["かく","kaku","to write"],
    ["はなす","hanasu","to speak"],["たべる","taberu","to eat"],["のむ","nomu","to drink"],["ねる","neru","to sleep"],
    ["おきる","okiru","to wake up"],["あう","au","to meet"],["かう","kau","to buy"],["まつ","matsu","to wait"],
    ["もつ","motsu","to hold"],["とる","toru","to take"],["つかう","tsukau","to use"],["つくる","tsukuru","to make"],
    ["およぐ","oyogu","to swim"],["ある","aru","to exist (thing)"],["いる","iru","to exist (living thing)"],["わかる","wakaru","to understand"],
    ["おおきい","ookii","big"],["ちいさい","chiisai","small"],["あたらしい","atarashii","new"],["ふるい","furui","old"],
    ["あつい","atsui","hot"],["さむい","samui","cold"],["たかい","takai","high / expensive"],["やすい","yasui","inexpensive"],
    ["おもしろい","omoshiroi","interesting"],["たのしい","tanoshii","fun"],["いそがしい","isogashii","busy"],["むずかしい","muzukashii","difficult"],
    ["やさしい","yasashii","kind / easy"],["かわいい","kawaii","cute"],["きれい","kirei","pretty / clean"],["しずか","shizuka","quiet"],
    ["ほん","hon","book"],["かばん","kaban","bag"],["くつ","kutsu","shoes"],["ふく","fuku","clothes"],
    ["じしょ","jisho","dictionary"],["てがみ","tegami","letter"],["てんき","tenki","weather"],["くもり","kumori","cloudy weather"],
    ["はれ","hare","clear weather"],["たいよう","taiyou","sun"],["こうえん","kouen","park"],["くうこう","kuukou","airport"],
    ["ほてる","hoteru","hotel"],["うち","uchi","home"],["くに","kuni","country"],["きって","kitte","postage stamp"],
    ["きっぷ","kippu","ticket"],["ざっし","zasshi","magazine"],["けっこん","kekkon","marriage"],["いっしょ","issho","together"],
    ["ちょっと","chotto","a little"],["ゆっくり","yukkuri","slowly"],["まっすぐ","massugu","straight ahead"],["きっさてん","kissaten","coffee shop"],
    ["いっぱい","ippai","full / one cup"],["りっぱ","rippa","splendid"],["せっけん","sekken","soap"],["きょうだい","kyoudai","siblings"],
    ["きゅうり","kyuuri","cucumber"],["しゅくだい","shukudai","homework"],["しょうゆ","shouyu","soy sauce"],["しょうが","shouga","ginger"],
    ["ちゅうごく","chuugoku","China"],["じてんしゃ","jitensha","bicycle"]
  ].map(([k,r,m,a])=>({k,r,m,a:a||[],u:[]}));


  window.KANA_SPRINT_LESSON = {
    appName: "Hiragana Sprint",
    scriptName: "Hiragana",
    scriptNameLower: "hiragana",
    storageKey: STORAGE_KEY,
    progressFileStem: "hiragana-sprint",
    progressVersion: 3,
    initialLearnUnlockedCount: 5,
    sampleKana: "あ",
    sampleWord: "ねこ",
    fontPreview: "あきさりふ",
    smallTsu: "っ",
    smallTsuFeature: "Small っ",
    fontProfiles: FONT_PROFILES,
    groups: GROUPS,
    visualConfusions: VISUAL,
    mnemonics: MNEMONICS,
    words: WORDS,
    extraWords: EXTRA_WORDS,
    testSpeech: {
      ja: "こんにちは。ひらがなの練習をしましょう。",
      en: "Meaning: school."
    }
  };
  window.KANA_SPRINT_LESSONS = window.KANA_SPRINT_LESSONS || {};
  window.KANA_SPRINT_LESSONS.hiragana = window.KANA_SPRINT_LESSON;
})();
